FROM node:20-alpine
WORKDIR /app

# We don't even need to copy or install here because docker-compose.override.yml
# mounts the host volume over /app and runs `npm install && npm run dev`.
# But for caching purposes, installing dependencies during build is faster.
COPY package.json package-lock.json* ./
RUN npm ci

EXPOSE 80
