// tests/e2e/bertFlow.e2e.test.js
// ============================================
// Live end-to-end flow against the REAL BERT service.
// Exercises: auth → chat (BERT NLP) → logs → insights (BERT) → reports → notifications.
//
// Requires the BERT service running (default http://127.0.0.1:8088).
// Run with:
//   RUN_BERT_E2E=true DB_DIALECT=sqlite DB_STORAGE=:memory: \
//   CHAT_AI_PROVIDER=bert INSIGHTS_AI_PROVIDER=bert NLP_DISABLE_FAST_PATH=true \
//   npx jest tests/e2e/bertFlow.e2e.test.js --runInBand
// ============================================

jest.mock('../../server/config/firebase', () => ({
  initializeFirebase: jest.fn(),
  getFirestore: jest.fn(() => null),
}));

const request = require('supertest');
const { app } = require('../../server/app');
const db = require('../../server/models');

const shouldRun = process.env.RUN_BERT_E2E === 'true';
const suite = shouldRun ? describe : describe.skip;

const { sequelize, User } = db;

suite('Live BERT E2E flow', () => {
  let token = '';
  const creds = { email: 'bert-e2e@example.com', password: 'Password123' };

  beforeAll(async () => {
    await sequelize.sync({ force: true });
    await User.create({
      username: 'bert_e2e_user',
      email: creds.email,
      hashed_password: creds.password, // hashed by model hook
      verified_email: true,
      is_active: true,
    });
    const login = await request(app).post('/api/auth/login').send(creds);
    expect(login.status).toBe(200);
    token = login.body.data.accessToken;
    expect(token).toBeTruthy();
  }, 60000);

  afterAll(async () => {
    await sequelize.close();
  });

  const auth = () => ({ Authorization: `Bearer ${token}` });

  test('chat logs a finance expense via BERT', async () => {
    const res = await request(app).post('/api/chat').set(auth()).send({ message: 'I spent 20 on lunch' });
    expect(res.status).toBe(200);
    expect(res.body.data.intent).toBe('log_finance');
    expect(res.body.data.engine).toBe('bert'); // proves it went through the BERT service
    expect(res.body.data.entities_logged.finance.length).toBeGreaterThanOrEqual(1);
  }, 30000);

  test('chat logs health steps via BERT', async () => {
    const res = await request(app).post('/api/chat').set(auth()).send({ message: 'I walked 8000 steps today' });
    expect(res.status).toBe(200);
    expect(res.body.data.intent).toBe('log_health');
    expect(res.body.data.entities_logged.health.length).toBeGreaterThanOrEqual(1);
  }, 30000);

  test('chat classifies a finance query through BERT (no entities)', async () => {
    const res = await request(app).post('/api/chat').set(auth()).send({ message: 'how much did I spend this week?' });
    expect(res.status).toBe(200);
    // BERT intent detection — query, not a log
    expect(['query_finance', 'get_insight', 'query_health']).toContain(res.body.data.intent);
    expect(res.body.data.entities_logged.finance.length).toBe(0);
  }, 30000);

  test('logged data is retrievable', async () => {
    const fin = await request(app).get('/api/finance').set(auth());
    expect(fin.status).toBe(200);
    expect(fin.body.data.length).toBeGreaterThanOrEqual(1);

    const health = await request(app).get('/api/health-logs').set(auth());
    expect(health.status).toBe(200);
    expect(health.body.data.length).toBeGreaterThanOrEqual(1);
  });

  test('dashboard insights are generated by BERT', async () => {
    const res = await request(app).get('/api/insights').set(auth());
    expect(res.status).toBe(200);
    const insights = res.body.data.insights;
    expect(insights).toBeTruthy();
    expect(insights.health_score).not.toBeNull();
    // model_used should reflect the BERT model (or fall back to statistical if BERT errored)
    expect(typeof insights.model_used).toBe('string');
  }, 60000);

  test('report generation + CSV download', async () => {
    const gen = await request(app).post('/api/reports/generate').set(auth());
    expect(gen.status).toBe(201);
    const id = gen.body.data.report.id;

    const csv = await request(app).get(`/api/reports/${id}/download?format=csv`).set(auth());
    expect(csv.status).toBe(200);
    expect(csv.headers['content-type']).toContain('text/csv');
    expect(csv.text).toContain('LifeSync Weekly Report');
  }, 60000);

  test('notifications were emitted for insight + report', async () => {
    const res = await request(app).get('/api/notifications').set(auth());
    expect(res.status).toBe(200);
    const types = res.body.data.map((n) => n.type);
    expect(types).toContain('report');
    expect(types).toContain('insight');
  });
});
